
server:  port: 8080

spring:  application:    name: 'loja'

eureka:  client:    register-with-eureka: true
    fetch-registry: true
    service-url:      defaultZone: https://localhost:8761/eureka